### PR TITLE
adjust marketplace methods to accept context

### PR DESCRIPTION
**Pull request by ricebin**
so it can support cancellations and timeouts

### CODE REVIEW

**Comment by adam-maj** [comment]
Thanks @ricebin, will take a look at this in more detail.

Would you be using the cancellations/timeouts on every query basically? Would they be different on a function-by-function basis or do you have the same preferences for every function?

Trying to think through ways we could expose this interface/make it generic without forcing everyone to input a context object to each function.

**Comment by ricebin** [comment]
> Thanks @ricebin, will take a look at this in more detail.
> 
> Would you be using the cancellations/timeouts on every query basically? Would they be different on a function-by-function basis or do you have the same preferences for every function?
> 
> Trying to think through ways we could expose this interface/make it generic without forcing everyone to input a context object to each function.

right.. we need it at per request level

**Comment by ricebin** [comment]
hi.. i was wondering what additional information i can provide to help this pr thru?
in golang, it is generally preferred to let the caller pass the context thru (instead of starting a new background context) in order to:
a. support tracing
b. cancellation
c. timeout
d. security
etc

thanks

**Comment by adam-maj** [comment]
> hi.. i was wondering what additional information i can provide to help this pr thru? in golang, it is generally preferred to let the caller pass the context thru (instead of starting a new background context) in order to: a. support tracing b. cancellation c. timeout d. security etc
> 
> thanks

Will move this branch to another one because tests aren't running on this external branch properly

**Pull request merged**
